### ISSUE TITLE
デザインの決定

### ISSUE THREAD

**Issue by fearless00589** [CDS-GH/Git-test#1]
基礎デザインの選定
- [ ] デザインA
- [ ] デザインB

**Comment by tatsuro-asn** [comment]
デザインはAで進めましょう

**Comment by tatsuro-asn** [comment]
みなさんはどう思いますか。顧客の反応を見る限りではAの方が適切かと判断しています。

**Comment by fearless00589** [comment]
作成効率を考慮するとBですが、Aの方が今後の拡張性はありそうですね

**Comment by tatsuro-asn** [comment]
了解です。それではAベースでいきましょう
